[project]
  name = "bytecode"
  description = "Python module to generate and modify bytecode"
  readme = "README.rst"
  requires-python = ">=3.11"
  license = { file = "COPYING" }
  authors = [{ name = "Victor Stinner", email = "victor.stinner@gmail.com" }]
  maintainers = [{ name = "Matthieu C. Dartiailh", email = "m.dartiailh@gmail.com" }]
  classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
  ]
  dependencies = ["typing_extensions;python_version<'3.10'"]
  dynamic = ["version"]


  [project.urls]
    homepage      = "https://github.com/MatthieuDartiailh/bytecode"
    documentation = "https://bytecode.readthedocs.io/en/latest/"
    repository    = "https://github.com/MatthieuDartiailh/bytecode"
    changelog     = "https://github.com/MatthieuDartiailh/bytecode/blob/main/doc/changelog.rst"


[build-system]
 requires      = ["hatchling>=1.27", "hatch-vcs>=0.5.0"]
 build-backend = "hatchling.build"

[dependency-groups]
 dev = [
   "mypy>=1.16.1",
   "pytest>=8",
   "pytest-cov>=6",
   "ruff>=0.12.0",
   "towncrier>=24.8",
 ]
 test = [
   "pytest>=8",
   "pytest-cov",
 ]

[tool.hatch.version]
 source = "vcs"

[tool.hatch.build.targets.wheel]
 packages = ["src/bytecode"]

[tool.towncrier]
 package = "bytecode"
 package_dir = "src"
 filename = "doc/changelog.rst"
 directory = "newsfragments"
 start_string = ".. towncrier release notes start\n"
 title_format = "{version} ({project_date})"
 issue_format = "#{issue}"
 underlines = ["-", "~", "^"]

 [[tool.towncrier.type]]
   directory = "feature"
   name = "Features"
   showcontent = true

 [[tool.towncrier.type]]
   directory = "bugfix"
   name = "Bugfixes"
   showcontent = true

 [[tool.towncrier.type]]
   directory = "doc"
   name = "Documentation"
   showcontent = true

 [[tool.towncrier.type]]
   directory = "removal"
   name = "Removals"
   showcontent = true

 [[tool.towncrier.type]]
   directory = "misc"
   name = "Miscellaneous"
   showcontent = true

 [[tool.towncrier.type]]
   directory = "security"
   name = "Security"
   showcontent = true

[tool.ruff]
  src            = ["src"]
  line-length    = 88

  [tool.ruff.lint]
    select        = ["B", "C", "E", "F", "W", "B9", "I", "C90", "RUF"]
    extend-ignore = ["E203", "E266", "E501", "F403", "F401", "RUF012", "RUF036"]

    [tool.ruff.lint.isort]
      combine-as-imports     = true
      extra-standard-library = ["opcode"]

    [tool.ruff.lint.mccabe]
      max-complexity = 43

[tool.mypy]
  follow_imports  = "normal"
  strict_optional = true

[tool.pytest.ini_options]
  minversion = "6.0"
