# This file is auto-generated by hatch-vcs do NOT edit it.

from collections import namedtuple

#: A namedtuple of the version info for the current release.
_version_info = namedtuple("_version_info", "major minor micro status")

parts = "0.1.dev2+gf39ee3331.d20260828".split(".", 3)
try:
   micro = int(parts[2])
except (IndexError, ValueError):
   micro = 0
status = parts[3] if len(parts) == 4 else ""
version_info = _version_info(
   int(parts[0]),
   int(parts[1]),
   micro,
   status,
)

# Remove everything but the 'version_info' from this module.
del namedtuple, _version_info, parts, micro, status

__version__ = "0.1.dev2+gf39ee3331.d20260828"
