name: Continuous Integration
on:
  schedule:
    - cron: '0 0 * * 2'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/ci.yml
      - bytecode/*
      - setup.py

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    env:
      TOXENV: fmt
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name: Run tox
        env:
          TOXENV: fnt
        run: |
          tox

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [py35, py36, py37, py38]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name: Run tox
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: |
          tox
