name: News fragment check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  newsfragment:
    name: Check Towncrier fragment
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Ensure a news fragment exists
        if: ${{ !contains(join(github.event.pull_request.labels.*.name, ','), 'no-news-required') }}
        env:
          BASE_REF: ${{ github.base_ref }}
        run: |
          git fetch origin "$BASE_REF" --depth=1
          python -m pip install --upgrade pip
          python -m pip install towncrier
          python -m towncrier check --compare-with "origin/$BASE_REF"
